schedules:
  save-updated-ticket:
    fixedDelay: 1800000 # 30분
    initialDelay: 60000 # 1분
  resend-ticket-completion-event:
    fixedDelay: 600000 # 10분
    initialDelay: 60000 # 1분
server:
  port: 8082
spring:
  application:
    name: ticket
  config:
    import:
      - classpath:/common/jpa.yml
      - classpath:/common/swagger.yml
      - classpath:/common/logging.yml
      - classpath:/common/kafka.yml
      - classpath:/common/zipkin.yml
      - classpath:/common/redis.yml
springdoc:
  paths-to-match:
    - "/tickets/**"


