schedules:
  resend-ticket-completed-event:
    fixed-delay: 600000 # 10분
    initial-delay: 60000 # 1분
server:
  port: 8082
spring:
  application:
    name: ticket
  config:
    import:
      - classpath:/common/jpa.yml
      - classpath:/common/swagger.yml
      - classpath:/common/logging.yml
      - classpath:/common/kafka.yml
      - classpath:/common/zipkin.yml
      - classpath:/common/redis.yml
springdoc:
  paths-to-match:
    - "/tickets/**"


